### ISSUE TITLE
Using max-height for content

### ISSUE THREAD

**Issue by lbineau** [DominikSerafin/vuebar#30]
Hi,
Thank you to contribute to VueJS ecosystem.

I wonder why max-height CSS rule instead of height rule doesn't work with vuebar. It would be convenient because a small amount of content doesn't need scrollbar and don't need to take so much space.
![image](https://user-images.githubusercontent.com/1534688/30853686-cbcf3d1e-a2af-11e7-9fe8-f0b2ee5e4f64.png)

**Comment by DominikSerafin** [comment]
Hey @lbineau, I dont understand what the issue is here. Could you describe it more in detail? Thanks!

**Comment by lbineau** [comment]
Hi @DominikSerafin I would want that it works the same this HTML example. (with max-height instead of height)
This way you don't need to force height.
https://codepen.io/lbineau/pen/xXqzmQ
I hope it is clear enough now :)

**Comment by DominikSerafin** [comment]
@lbineau thanks for the description. Have you actually tried to do that in your project and it didn't work? The example in the doc has `height` instead of `max-height` to show that there's an empty space.

**Comment by DominikSerafin** [comment]
@lbineau it isn't something that Vuebar supports 100%. Maybe try wrapping your container with Vuebar into another container with `max-height`?

**Comment by velenoise** [comment]
Just for the record, I managed to use the lib with max-height with a few tweaks: 

1) I replaced every occurrence of `state.el2.clientHeight` with `state.el1.clientHeight`. When height is explicitly set they are both the same, but with max-height only the parent will return the correct info. 

2) Instead of setting the `state.el2.style.height = '100%'`, I followed [this idea](https://stackoverflow.com/a/32886502) and changed el1 to a flexbox layout. So my styles ended up like:

```
state.el1.style.position = 'relative';
state.el1.style.overflow = 'hidden';
state.el1.style.display = 'flex';
state.el1.style.flexDirection = 'column';

state.el2.style.display = 'block';
state.el2.style.overflowX = 'hidden';
state.el2.style.overflowY = 'scroll';
state.el2.style.flex = '0 1 auto';
```

While this solved my particular case, I'm not sure whether or not it breaks any other situation. If you're interested I may open a pull request so it can be better evaluated.

**Comment by HawkeyePierce89** [comment]
I think it's need add to README

**Comment by netleader** [comment]
This solved my problem too. tried two days without success before.
Thanks, this should be definitely in the docs!

**Comment by jhlee8804** [comment]
@velenoise You saved my life...

**Comment by maulpets** [comment]
For anyone using this solution may notice it doesnt work in IE11.   I added a media query to target IE11/10 then specified a height inside.
```

.wrapper{
max-height: 40vh;
}
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
  .wrapper{
       height: 40vh;
    }
}
```
