### ISSUE TITLE
Not working in Nuxt

### ISSUE THREAD

**Issue by UltramarineLights** [DominikSerafin/vuebar#62]
Hi! I'm trying to get vuebar to work in Nuxt but it does not work, I can see all the code is added through the inspector but no result, could it be due to the layout functionality of Nuxt? Thank you

**Comment by mavrick** [comment]
What is the error and what version of nuxt are you using @UltramarineLights ?

**Comment by UltramarineLights** [comment]
It does not give an error, it simply doesn't display even if all the code added by the directive is there in the browser inspector. I'm using the latest Nuxt 1 version.

**Comment by zeknoss** [comment]
Hello @UltramarineLights ,
In order to make vue-bar work with Nuxt, you need to create a plugin and add it to the configuration, then you're good to go.

Here's how you do it:
1. Create a vue-bar.js with following content:
```
import Vue from 'vue';
import Vuebar from 'vuebar';

Vue.use(Vuebar);
```

2. Add the plugin to the nuxt.config.js
```
...
    /**
    ** Plugins to load before mounting the App
    */
    plugins: [
       ...
        '~/plugins/vue-bar',
        ...
    ],
...
```
3. Now you can use the plugin normally

Let us know if you have any problems.

Cheers!

**Comment by DominikSerafin** [comment]
Hi @zeknoss, thanks for providing help on this issue ❤
