### ISSUE TITLE
Absolute positioned items within 'v-bar' are fixed and do not scroll

### ISSUE THREAD

**Issue by alucidwolf** [DominikSerafin/vuebar#73]
I am building a website viewer and control bar, using this tool for the scrolling area of the website.

Some sites have absolute positioned navigation elements over a carousel, so the navigation does not scroll with the rest of the page, but instead acts as a fixed element.

I took one of your fiddles and modified it for a visual here:
http://jsfiddle.net/theBDank/c9ofytu5/4/

Have you or anyone else experience this and have a possible workaround?

BEST Vue plugin for scrolling by far from what I have seen. Cheers!

**Comment by DominikSerafin** [comment]
Hi @alucidwolf, I'm glad you like Vuebar =) 

Your issue is probably related to Vuebar styling its first element using `position: relative`, which is needed for its functionality.

I quickly looked through your fiddle and I think it can be fixed by wrapping elements inside with another element also with `position: relative;` - http://jsfiddle.net/05t79be4/
